# Generated by Django 4.0.3 on 2023-07-31 18:45

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_box', '0002_answer_question_quiz_delete_categories_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
