# Generated by Django 4.0.3 on 2023-04-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
