# Generated by Django 3.2 on 2023-07-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
